stages:
  - deploy

push_to_github:
  stage: deploy
  tags:
    - gitlab-to-github
  script:
    - whoami
    - git clone --bare https://code.ihep.ac.cn/zdzhang/hai.git
    - cd hai.git
    - git push --mirror git@github.com:zhangzhengde0225/hai.git
    - cd ..
    - rm -rf hai.git
  only:
    - main
  before_script:
    - cd /tmp/workspace
  cache:
    paths:
      - /tmp/workspace
    